#!/usr/bin/env bash
# WARNING: Do not edit this file directly in your own repository.
# It is maintained in the grails-plugin-template repository.
# To make changes, edit it there and they will be synced automatically:
# https://github.com/grails-plugins/grails-plugin-template/tree/main/.github/scripts
#
# Commit the given paths and get them onto the base branch, whether or not that
# branch is protected.
#
# A workflow that writes back to its own repo cannot assume it may push to the
# default branch: repos with branch protection reject the push and the whole job
# fails. This helper tries the direct push first — so unprotected repos keep the
# zero-friction behaviour and produce no PR noise — and only if that is rejected
# does it park the commit on a chore branch and open a pull request.
#
# Environment:
#   COMMIT_MESSAGE  required  commit subject (include [skip ci] if wanted)
#   PR_BRANCH       required  chore branch to use for the pull-request fallback
#   PR_TITLE        required  pull request title
#   PR_BODY         optional  pull request body
#   BASE_BRANCH     optional  PR base; defaults to the currently checked-out branch
#   GH_TOKEN        required for the fallback path only (gh authentication)
#   MERGE_WAIT_SECONDS optional  how long to wait for checks when the repo has
#                                auto-merge disabled (default 900)
#
# Arguments: the paths to stage, e.g. `project.yml`.

set -euo pipefail

: "${COMMIT_MESSAGE:?COMMIT_MESSAGE is required}"
: "${PR_BRANCH:?PR_BRANCH is required}"
: "${PR_TITLE:?PR_TITLE is required}"

if [ "$#" -eq 0 ]; then
    echo "usage: $0 <path> [<path>...]" >&2
    exit 2
fi

if git diff --quiet -- "$@"; then
    echo "No changes in $* to commit"
    exit 0
fi

base_branch="${BASE_BRANCH:-$(git rev-parse --abbrev-ref HEAD)}"
if [ "${base_branch}" = "HEAD" ]; then
    echo "Detached HEAD and no BASE_BRANCH given — cannot determine the branch to update" >&2
    exit 1
fi

git config user.name  "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add -- "$@"
git commit -m "${COMMIT_MESSAGE}"

if git push origin "HEAD:refs/heads/${base_branch}"; then
    echo "Pushed directly to ${base_branch}"
    exit 0
fi

echo "Direct push to ${base_branch} was rejected (branch protection?) — opening a pull request instead"

# The chore branch is disposable: it only ever carries this one commit on top of
# the base branch, so force-pushing it just refreshes a superseded proposal.
git push --force origin "HEAD:refs/heads/${PR_BRANCH}"

existing=$(gh pr list --head "${PR_BRANCH}" --base "${base_branch}" --state open --json url --jq '.[0].url // ""')
if [ -n "${existing}" ]; then
    echo "Updated existing pull request ${existing}"
    pr_url="${existing}"
else
    pr_url=$(gh pr create \
        --head "${PR_BRANCH}" \
        --base "${base_branch}" \
        --title "${PR_TITLE}" \
        --body "${PR_BODY:-${PR_TITLE}}")
    echo "Opened pull request ${pr_url}"
fi

# --- land the pull request ---------------------------------------------------
# Preferred path: auto-merge, which lands the PR as soon as any required checks
# pass without holding this runner open.
if gh pr merge "${pr_url}" --squash --auto --delete-branch; then
    echo "Auto-merge enabled on ${pr_url}"
    exit 0
fi

# Auto-merge is not available — most often because the repository has "Allow
# auto-merge" switched off. Do the waiting here instead of leaving the PR for a
# human: watch the checks, then merge directly.
echo "Auto-merge unavailable — waiting for checks on ${pr_url}, then merging directly"

# Checks attach to the PR shortly after it is opened; watching too early makes
# gh report "no checks reported" and return before any have registered.
sleep 20

wait_seconds="${MERGE_WAIT_SECONDS:-900}"
timeout "${wait_seconds}" gh pr checks "${pr_url}" --watch --fail-fast \
    || echo "Checks did not all pass, timed out after ${wait_seconds}s, or none are configured" \
            "— attempting the merge anyway; branch protection remains the authority"

if gh pr merge "${pr_url}" --squash --delete-branch; then
    echo "Merged ${pr_url}"
else
    echo "::warning::Could not merge ${pr_url} automatically — merge it manually"
fi
